altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  dd27d2b4-acc4-45bb-95a8-51b9417b814c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-26T02:35:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 82884296-8240-4ebf-a074-f136aa598089
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f4283ead-5e5c-4ce4-b8f2-7a0ee3a65c17
        userCondition: null
fs: assetBaseUrl
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
